### ISSUE TITLE
[BUG] Username not in database

### ISSUE THREAD

**Issue by rishithab48** [WSU-4110/Novelology#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user creates an account with an email, their username isn't saved.
![Bug](https://github.com/WSU-4110/Novelology/assets/100251123/74cbdd60-1e08-4f26-8e53-1e95d0871b42)

When a user creates an account with Google, not redirecting to the onboarding page. (Probably have to change the navigate route).

### Expected Behavior

When a user creates an account, their username needs to be saved in the database and displayed on their profile.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by racecn** [comment]
is this a new seperate bug you've found?

`When a user creates an account with Google, not redirecting to the onboarding page. (Probably have to change the navigate route).`

**Comment by rishithab48** [comment]
Yeah I tested the login with Google and it doesn't navigate to the onboarding page.
