### ISSUE TITLE
[BUG] sign_up broken functionalities

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User is not provided with feedback if their username, or password is valid

### Expected Behavior

User should be reminded if their password is not properly formatted
or if a field is not filled out

### Steps To Reproduce

1. Run project
2. log out
3. attempt to create a new account

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by rishithab48** [comment]
User is given a feedback about their username and password.
