### ISSUE TITLE
FR14. Book Purchase Links

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#16]
|FR14. Book Purchase Links|
|---|
|**Goal**: To provide users the ability to purchase the book they want, without searching it up on a different website.
**Stakeholders:** All|
| **Description:** If a user likes a book or they saw a post about that book, they will have a link below the book that will send them to the book purchase website.|
| **Origin:** Based on the project proposal.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 2 |

**Comment by rishithab48** [comment]
Users can now see the book purchase links on the book information page. If the purchase link is not available, it says not available.
