### ISSUE TITLE
[BUG] Onboarding doesnt use RTE

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/WSU-4110/Novelology/assets/35074638/17460f77-66f0-4956-8cc1-7e8c46eb6455)

### Expected Behavior

Should have the react-quill editor importable w/ <TextEditor/ >  in components

### Steps To Reproduce

1. create a new account

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by rishithab48** [comment]
Yes, it doesn't use RTE. User will have the option to modify their bio with RTE in the settings after they create the account.
