### ISSUE TITLE
[BUG] BookList page is not reactive

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/WSU-4110/Novelology/assets/35074638/c619721e-e481-4ea4-bf3a-4e2a0c7641a5)

### Expected Behavior

Should work on all media sizes

### Steps To Reproduce

1. run w/ smaller phone

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by rishithab48** [comment]
BookList page sets itself according to the page dimensions.
