### ISSUE TITLE
FR15. Book Stack Creation

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#17]
|FR15. Book Stack Creation|
|---|
|**Goal**: To provide readers the ability to make personalized book lists.
**Stakeholders:** Readers|
| **Description:** Often while reading, readers want to keep track of all the books they read. This book stack feature will allow readers to curate their book lists.|
| **Origin:** Based on the project proposal.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 2 |

**Comment by rishithab48** [comment]
Completed it.
