### ISSUE TITLE
FR16. Book Stack Editing

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#18]
|FR16. Book Stack Editing|
|---|
|**Goal**: To allow readers the ability to edit and update their book lists.
**Stakeholders:** Readers|
| **Description:** This option enables readers to edit their book stacks to add or remove specific books, or change the title of the list.|
| **Origin:** Based on the project proposal.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 2 |

**Comment by rishithab48** [comment]
All the required conditions are satisfied. Readers can add, and remove books from book lists. They have the option to change the title of the book list.
