### ISSUE TITLE
FR17. Book Stack Privacy Settings

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#19]
|FR17. Book Stack Privacy Settings|
|---|
|**Goal**: The privacy settings option enables users to control the visibility of their list.
**Stakeholders:** Readers|
| **Description:** Readers who don’t want certain lists to be seen by the public can change the visibility of their book stacks. This will be available in the book list settings.|
| **Origin:** Discussed in the 01/28/24 meeting|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:**3 |

**Comment by rishithab48** [comment]
Completed. Reader has an option to have public or private book lists.
