### ISSUE TITLE
FR18. Book Rating System

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#20]
|FR18. Book Rating System|
|---|
|**Goal**: For readers to be able to rate a book
**Stakeholders:** Reviewers, Readers|
| **Description:** Readers, and reviewers will be able to rate a book through a five-star rating system. The scale will be from 1 to 5 stars, with 1 being the worst and 5 being the best. This system will be quick to complete and easy to interpret for users who wish to get quick user/customer feedback. However, a reviewer's feedback will have special significance over a reader’s.|
| **Origin:** Based on the project proposal.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 2|

**Comment by rishithab48** [comment]
All the tasks are completed for this FR.
