### ISSUE TITLE
FR20. Book Search

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#22]
|FR20. Book Search|
|---|
|**Goal**: Users can use this option to search books and get all the necessary information about them.
**Stakeholders:** All|
| **Description:** A search bar will be present at the top of the page at all times so that users can search for a book and get a list of books that satisfy the search condition. Through this list, the user can choose their desired option and get all the necessary data about it.|
| **Origin:** Based on the project proposal.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 1 |

**Comment by rishithab48** [comment]
Book search works with books and authors.
