### ISSUE TITLE
FR26. Account Deactivation

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#28]
|FR26. Account Deactivation|
|---|
|**Goal**: To successfully deactivate a user’s account
**Stakeholders:** All|
| **Description:** By deactivating a user’s account, their profile will no longer be visible online and will not be searchable. This gives the users an alternative option to deleting.|
| **Origin:** From group meeting on 01/29/24|
| **Version:** 1.0 |
|**Date:** 01/29/24
| **Priority:** 4 |

**Comment by rishithab48** [comment]
Planned to execute it but couldn't get to it before due date.
