### ISSUE TITLE
NFR2. Ease of Use

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#37]
|NFR2. Ease of Use|
|---|
|**Goal**: Allow users of the platform to quickly, and intuitively navigate and use the tools Novelology provides them.
**Stakeholders:** All|
| **Description:** By implementing simple design blocks, icons, and recognizable social media layouts, we can minimize the learning curve any new user would need to overcome to become comfortable on the platform. By reducing the effort a user would need to acclimate to Novelology, we can increase their satisfaction and usage time.|
| **Origin:** From talks during the 1/28/24 meeting to develop platform requirements.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 1 |

**Comment by rishithab48** [comment]
The UI is simplistic and easy to use and navigate for users.
