### ISSUE TITLE
NFR4. External API Integration

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#39]
|NFR4. External API Integration|
|---|
|**Goal**: Our platform will successfully implement external APIs so that users have access to quality content on demand.
**Stakeholders:** All|
| **Description:** Novelology will access APIs such as Google Books, so that the burden of storing large amounts of information about every book is off-site, allowing our team to focus on implementing our functional requirements. These API connections will be made with low downtime and small amounts of API calls.|
| **Origin:** From talks during the 1/28/24 meeting to develop platform requirements.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 1 |

**Comment by rishithab48** [comment]
Google and Library APIs are integrated to the system.
