### ISSUE TITLE
NFR5. Data Management

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#40]
|NFR5. Data Management|
|---|
|**Goal**: Establish efficient procedures for organization of platform-related data.
**Stakeholders:** All|
| **Description:** Effective and proper management of both user data and externally sourced data is incredibly important to ensure the accuracy of results on a specific book a user would like to learn more about– as well as to ensure the speed at which queries are made to the site. |
| **Origin:** From talks during the 1/28/24 meeting to develop platform requirements.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 1 |

**Comment by rishithab48** [comment]
All the data is stored in a proper format on firebase.
