### ISSUE TITLE
NFR6. Data Security

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#41]
|NFR6. Data Security|
|---|
|**Goal**: Ensure that all data held on our platform’s database is of limited score, and only used for internal functions.
**Stakeholders:** All|
| **Description:** This aims to safeguard all user data stored on Novelology’s database platform by implementing strict limits to data access and usage. We furthermore will prevent any unauthorized access, modification, or publication of any user data stored within the database.|
| **Origin:** From meetings about application design on 1/28/24.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 1 |

**Comment by rishithab48** [comment]
All the above conditions are met. Firebase also adds extra layer of security.
