### ISSUE TITLE
FR5. Author Verification

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#7]
|FR5. Author Verification|
|---|
|**Goal**: To verify an author’s profile/account.
**Stakeholders:** Authors|
| **Description:** For authors to interact with their readers, authors need to become verified. Verification makes it possible for readers to locate and follow their favorite authors and keeps them from following accounts that are counterfeits. To become verified, authors will be required to submit proof of identification (Driver’s license, State ID, birth certificate, etc.)  |
| **Origin:** Based on the meeting on 01/28/24.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 3 |

**Comment by rishithab48** [comment]
Author verification is completed. Author name is saved in the database
