### ISSUE TITLE
FR6. Author Profile Page

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#8]
|FR6. Author Profile Page|
|---|
|**Goal**: This page contains the Author’s profile and bio.
**Stakeholders:** Authors|
| **Description:** The Author profile page will have the Author’s name, author tag, bio, profile picture, background picture, information about their followers and following, along with a follow button. Additionally, this page also has a list of their published books and their activity.|
| **Origin:**  Based on the meeting on 01/28/24.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 2 |

**Comment by rishithab48** [comment]
Author profile page shows everything mentioned in the description.
