### ISSUE TITLE
FR7. Reader Profile Page

### ISSUE THREAD

**Issue by racecn** [WSU-4110/Novelology#9]
|FR7. Reader Profile Page|
|---|
|**Goal**: This page contains the reader’s profile and information
**Stakeholders:** Readers|
| **Description:** The Reader profile page will have the reader’s name, self-assigned labels, bio, profile picture, background picture, and information about their followers and following, along with a follow button, favorite genres, reading stats, and reading challenges(optional). Additionally, this page consists of the reader’s personalized book lists and their post interactions.|
| **Origin:** Based on the meeting on 01/28/24.|
| **Version:** 1.0 |
|**Date:** 01/28/24
| **Priority:** 2 |

**Comment by rishithab48** [comment]
All the information mentioned in the description is shown on Reader profile page.
